add_newline = false

#Replace the "❯" symbol in the prompt
[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"
vicmd_symbol = "&"
use_symbol_for_status = false

# The line_break module separates the prompt into two lines.
[line_break]
disabled = true

[username]
format = "[$user]($style)"
style_user = "nrd yellow"
show_always = true

[hostname]
format =  "@[$hostname]($style) "
style = "bold grey"
ssh_only = false
disabled = false

[directory]
truncation_length = 5

[git_branch]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

